name: Sync Locales to lation_247robbery

on:
  push:
    branches:
      - main
    paths:
      - 'lation_247robbery/**'
  workflow_dispatch:

jobs:
  sync-locales:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout translations repository
        uses: actions/checkout@v3

      - name: Clone target repository
        run: |
          git clone https://github.com/IamLation/lation_247robbery.git target_repo
          cp -r lation_247robbery/* target_repo/locales/
          cd target_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(locales): automated sync from translations repo"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/IamLation/lation_247robbery.git main
