name: Sync Locales to Repositories

on:
  push:
    branches:
      - main
    paths:
      - 'lation_247robbery/**'
      - 'lation_mining/**'
      - 'lation_weed/**'
  workflow_dispatch:

jobs:
  sync-247robbery:
    if: contains(github.event.head_commit.message, 'lation_247robbery') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout translations repository
        uses: actions/checkout@v3

      - name: Clone target repository
        run: |
          git clone https://github.com/IamLation/lation_247robbery.git target_repo
          cp -r lation_247robbery/* target_repo/locales/
          cd target_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(locales): automated sync from translations repo"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/IamLation/lation_247robbery.git main

  sync-mining:
    if: contains(github.event.head_commit.message, 'lation_mining') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout translations repository
        uses: actions/checkout@v3

      - name: Clone target repository
        run: |
          git clone https://github.com/IamLation/lation_mining.git target_repo
          cp -r lation_mining/* target_repo/locales/
          cd target_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(locales): automated sync from translations repo"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/IamLation/lation_mining.git main

  sync-weed:
    if: contains(github.event.head_commit.message, 'lation_weed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout translations repository
        uses: actions/checkout@v3

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/IamLation/lation_weed.git target_repo
          cp -r lation_weed/* target_repo/locales/
          cd target_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(locales): automated sync from translations repo"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/IamLation/lation_weed.git main
